In [2]:
import numpy as np

a = np.array([0,1,2,3]) # вектор
b = np.array([4,5,6,7]) # вектор 2
c = np.array([[0,1,2,3],
             [4,5,6,7]]) # матрица
   

In [3]:
# матрица 2 x 4, заполненная нулями
d = np.zeros((2,4)) 

# матрица 2 x 5, заполненная случайными числами от 0 до 1
e = np.random.rand(2, 5) 

In [4]:
print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.46126949 0.69744261 0.67971441 0.81474045 0.11815645]
 [0.4444697  0.40419272 0.28906387 0.97406111 0.27083371]]


In [5]:
# каждый элемент вектора умножается на 0.1
print(a * 0.1)

[0.  0.1 0.2 0.3]


In [6]:
# каждый элемент матрицы умножается на 0.2
print(c * 0.2)

[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]


In [7]:
# поэлементное умножение a на b
print(a * b)

[ 0  5 12 21]


In [8]:
# поэлементное умножение и x0.2
print(a * b * 0.2)

[0.  1.  2.4 4.2]


In [9]:
# поэлементное умножение вектора a с каждой строкой 
# матрицы с, посколько имеет то же число столбцов, что и a
print(a * c)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [10]:
# разное число столбцов - ошибка
print(a * e)

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [27]:
x = np.zeros((1, 4))
y = np.zeros((4,3))

z = x.dot(y)
print(z.shape)
print(x)

(1, 3)
[[0. 0. 0. 0.]]


In [15]:
import numpy as np

a = np.array([2,1,2,3]) # вектор

b = np.array([4,5,6,7]) # вектор 2

c = np.array([[0,1,2,3],
             [4,5,6,7]]) # матрица

print(a * b)

[ 8  5 12 21]


In [17]:
k = a.dot(b)
print(k)

46


In [20]:
j = b.dot(a)
print(j)

46


In [21]:
print(a * c)

[[ 0  1  4  9]
 [ 8  5 12 21]]


In [30]:
a1 = np.array([a])
print(a1.shape)

print(a1.dot(c.T))

(1, 4)
[[14 46]]
