In [16]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # вернет x если он положительный либо 0

def relu2deriv(output):
    return output > 0 # возвращает 1 если больше нуля, иначе 0

alpha = 0.2

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

#weights_1 = 2 * np.random.random((3, 4)) - 1
#weights_2 = 2 * np.random.random((4, 1)) - 1


weights_1 = np.array([ [ -0.2,  0.4, -0.9, -0.4 ],
                       [ -0.7, -0.8, -0.6, -0.3 ],
                       [ -0.2, 0.1, -0.2,  0.4 ] ] )

weights_2 = np.array([ [ -0.6, 0.7, -0.9, 0.3 ] ]).T


for iteration in range(1):
    sum_error = 0
    
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1] # чтобы получить массив вида [[1, 0, 1]] вместо [1, 0, 1]
        layer_1 = relu(np.dot(layer_0, weights_1))        
        layer_2 = np.dot(layer_1, weights_2)
        
        sum_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        
        delta_2 = walk_vs_stop[i:i+1] - layer_2
        delta_1 = delta_2.dot(weights_2.T)*relu2deriv(layer_1)
        print("delta_1:\n ", delta_1)
        
        print("layer_0.T:\n ", layer_0.T)
        
    #    print("layer_1.T:\n ", layer_1.T)
            
        weights_2 += alpha * layer_1.T.dot(delta_2)
        weights_1 += alpha * layer_0.T.dot(delta_1)  
        
       # print("layer_1.T.dot(delta_2):\n ", layer_1.T.dot(delta_2))
        print("layer_0.T.dot(delta_1):\n ", layer_0.T.dot(delta_1))
        print("layer_0.T.dot(delta_1):\n ", np.dot(layer_0.T, delta_1))
                
    print(sum_error)
       

delta_1:
  [[-0.     0.455 -0.     0.   ]]
layer_0.T:
  [[1]
 [0]
 [1]]
layer_0.T.dot(delta_1):
  [[-0.     0.455 -0.     0.   ]
 [-0.     0.    -0.     0.   ]
 [-0.     0.455 -0.     0.   ]]
layer_0.T.dot(delta_1):
  [[-0.     0.455 -0.     0.   ]
 [-0.     0.    -0.     0.   ]
 [-0.     0.455 -0.     0.   ]]
delta_1:
  [[-0.     0.    -0.     0.291]]
layer_0.T:
  [[0]
 [1]
 [1]]
layer_0.T.dot(delta_1):
  [[-0.     0.    -0.     0.   ]
 [-0.     0.    -0.     0.291]
 [-0.     0.    -0.     0.291]]
layer_0.T.dot(delta_1):
  [[-0.     0.    -0.     0.   ]
 [-0.     0.    -0.     0.291]
 [-0.     0.    -0.     0.291]]
delta_1:
  [[ 0.         -0.22373502  0.         -0.09341303]]
layer_0.T:
  [[0]
 [0]
 [1]]
layer_0.T.dot(delta_1):
  [[ 0.         -0.          0.         -0.        ]
 [ 0.         -0.          0.         -0.        ]
 [ 0.         -0.22373502  0.         -0.09341303]]
layer_0.T.dot(delta_1):
  [[ 0.         -0.          0.         -0.        ]
 [ 0.         -0.          

In [51]:
relu2deriv(np.array([5, -4, 7]))

array([ True, False,  True])